# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Anderson Felix
tagline:             'Front-end Developer'
description:         
url:                 http://andersonfelix.com.br
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Anderson Felix
  url:               https://twitter.com/anderson_felix
  email:             anderson.felix83@gmail.com

# Custom vars
version:             1.0.0